houses/urls.py
from django.urls import path

from . import views

app_name = 'houses_visual'

urlpatterns = [
    path('crear/', views.visual_create, name='create')
]

invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices_visual'

urlpatterns = [
    path('pagar', views.visual_pay, name='pay'),
    path('listar', views.visual_list, name='list'),
]

water_control/urls.py
from django.contrib import admin
from django.urls import include, path


from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('water_control.routes')),
    path('jefes-de-familia/', include('family_bosses.urls')),
    path('casas/', include('houses.urls')),
    path('medidores/', include('measurers.urls')),
    path('recibos/', include('invoices.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

invoices/models.py
from decimal import Decimal

from django.db import models

from django.db.models.signals import pre_save

from family_bosses.models import FamilyBoss
from houses.models import House
from consumption_histories.models import ConsumptionHistory

from django.utils import timezone

class Invoice(models.Model):
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    client = models.ForeignKey(FamilyBoss, on_delete=models.CASCADE)
    place = models.ForeignKey(House, on_delete=models.CASCADE)
    paid = models.BooleanField(default=False)
    payment_date = models.DateTimeField(null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=500, default='', blank=True)
    detail = models.ForeignKey(ConsumptionHistory, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {} : {}'.format(self.client, self.place, self.created_at)

    def pay(self):
        self.paid = True
        self.payment_date = timezone.now()
        self.save()

def set_amount(sender, instance, *args, **kwargs):
    if instance.amount is None:
        price_per_mts3 = 1250
        price_without_consumption = 100
        #¡TEMPORAL!# Estas variables hay que colocarlas en la interfaz

        if instance.detail.consumption > 0:
            instance.amount = Decimal(instance.detail.consumption * price_per_mts3)
        else:
            instance.amount = Decimal(price_without_consumption)

pre_save.connect(set_amount, sender=Invoice)

invoices/routes.py
from django.urls import path

from . import views

app_name = 'invoices'

urlpatterns = [
    path('year/<int:year>/', views.InvoiceListView.as_view(), name='list_year'),
    path('year/<int:year>/month/<int:month>/', views.InvoiceListView.as_view(), name='list_month'),
    path('year/<int:year>/month/<int:month>/day/<int:day>/', views.InvoiceListView.as_view(), name='list_day'),
]

invoices/views.py
from django.shortcuts import render

from rest_framework.views import APIView
from rest_framework.response import Response

from .serializers import InvoiceSerializer
from .models import Invoice

from rest_framework import status

from .utils import get_range_date

from datetime import datetime

from django.contrib.auth.decorators import login_required
from rest_framework import permissions

class InvoiceListView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = InvoiceSerializer

    def get(self, request, year, month=None, day=None, *args, **kwargs):
        try:
            invoices = self.get_queryset(year,month,day)
        except ValueError:
            return Response(status=status.HTTP_400_BAD_REQUEST)
        serializer = self.serializer_class(invoices, many=True)
        return Response(serializer.data)

    def get_queryset(self, year, month, day):
        from_date, to_date = get_range_date(year, month, day)
        invoices = Invoice.objects.filter(created_at__range=(from_date, to_date))
        return invoices


@login_required()
def visual_pay(request):
    return render(request, 'invoices/pay.html')

@login_required()
def visual_list(request):
    return render(request, 'invoices/list.html', {'current_year': datetime.now().year})

invoices/templates/invoices/snippets/form.html
<form id='searchInvoices' action="{% url 'familyboss-pending-invoices' 12345 %}">
    <div class="form-group">
        <div class="input-group">
            <input type="number" class="form-control" placeholder="identificacion del cliente" id="card_id" name="card_id">
            <div class="input-group-append">
              <button class="btn btn-primary">Consultar</button>
            </div>
          </div>        
    </div>
</form>

invoices/templates/invoices/snippets/form_date.html
<form id="formListInvoice" action="{% url 'invoices:list_year' 12345 %}">
    <div class="form-group">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm12 input-group mt-2">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="year">Año:</label>
                </div>
                <input api='water_control' class="form-control" type="number" name="year" id="year" placeholder="ingrese un año" min="1900"  max="{{ current_year }}">
            </div>
            <div class="col-lg-4 col-md-6 col-sm12 input-group mt-2">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="month">Mes:</label>
                </div>
                <select api='water_control' class="form-control" name="month" id="month" disabled>
                    <option value="0">Todos</option>
                    <option value="1">Enero</option>
                    <option value="2">Febrero</option>
                    <option value="3">Marzo</option>
                    <option value="4">Abril</option>
                    <option value="5">Mayo</option>
                    <option value="6">Junio</option>
                    <option value="7">Julio</option>
                    <option value="8">Agosto</option>
                    <option value="9">Septiembre</option>
                    <option value="10">Octubre</option>
                    <option value="11">Noviembre</option>
                    <option value="12">Diciembre</option>
                </select>
            </div>
            <div class="col-lg-4 col-md-6 col-sm12 input-group mt-2">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="day">Día:</label>
                </div>
                <select api='water_control' class="form-control" name="day" id="day" disabled>
                    <option value="0">Todos</option>
                </select>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary" id="submit" disabled>Consultar Facturas</button>
</form>

invoices/templates/invoices/snippets/invoice.html
<div class="card">
    <div class="card-header">
      <h5 class="card-title">Ticket de Pago</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="card-title">
          Nombre: Jose Castillo
        </div >
      </div>
      <div class="row">
        <div class="card-title">
          Concepto: 1000 mts3
        </div >
      </div>
      <div class="row">
        <div class="card-title">
          Estado: Pagado
        </div >
      </div>
    </div>
  </div>