family_bosses/urls.py
from django.urls import path

from . import views

app_name = 'family_bosses_visual'

urlpatterns = [
    path('crear/', views.visual_create, name='create'),
    path('editar/', views.visual_edit, name='edit'),
]

houses/urls.py
from django.urls import path

from . import views

app_name = 'houses_visual'

urlpatterns = [
    path('crear/', views.visual_create, name='create')
]

invoices/urls.py
from django.urls import path

from . import views

app_name = 'invoices_visual'

urlpatterns = [
    path('pagar', views.visual_pay, name='pay'),
    path('listar', views.visual_list, name='list'),
]

measurers/urls.py
from django.urls import path

from . import views

app_name = 'measurers_visual'

urlpatterns = [
    path('actualizar/', views.visual_update, name='update')
]

water_control/urls.py
from django.contrib import admin
from django.urls import include, path


from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('water_control.routes')),
    path('jefes-de-familia/', include('family_bosses.urls')),
    path('casas/', include('houses.urls')),
    path('medidores/', include('measurers.urls')),
    path('recibos/', include('invoices.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Control de Agua</title>
    {% block css %}
    {% endblock %}
</head>
<body>
    {% include 'navbar.html' %}
    <div class="mt2" id="InfoMsg"></div>
    <div class="container">
        <div class="row mt-3">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <footer class="mt-4"></footer>
</body>
<script src="{% static 'js/utils.js' %}"></script>
<script src="{% static 'js/templates.js' %}"></script>
<script src="{% static 'js/loading.js' %}"></script>
<script src="{% static 'js/forms.js' %}"></script>
{% block javascript %}
{% endblock %}
<script src="https://kit.fontawesome.com/7efd9e34c5.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="col">
        <div class="h2 font-weight-bold">Bienvenido a Control de Aguas</div>
        <p>
            Selecciona entre una de las distintas opciones del panel superior
        </p>
    </div>
{% endblock %}

templates/navbar.html
{% url 'houses_visual:create' as house_create %}
{% url 'family_bosses_visual:create' as family_create %}
{% url 'family_bosses_visual:edit' as family_edit %}
{% url 'measurers_visual:update' as measurer_update %}
{% url 'invoices_visual:pay' as invoice_pay %}
{% url 'invoices_visual:list' as invoice_list %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Acme</a>

    <button type='button' name='button' class="navbar-toggler navbar-toggler-right" data-toggle='collapse' data-target="#navb">
        <span class="fas fa-align-justify"></span>
    </button> 

    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == house_create %}active{% endif %}">
                <div class="dropdown">
                    <div class="nav-link" data-toggle="dropdown">Casas<i class="fas fa-home"></i> </div>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{{ house_create }}">Registrar</a>
                    </div>
                </div>
            </li>
            <li class="nav-item {% if request.path == family_create %}active{% endif %}">
                <div class="dropdown">
                    <div class="nav-link" data-toggle="dropdown">Familias <i class="fas fa-users"></i></div>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{{ family_create }}">Registrar</a>
                      <a class="dropdown-item" href="{{ family_edit }}">Editar/Eliminar</a>
                    </div>
                </div>
            </li>
            <li class="nav-item {% if request.path == measurer_update %}active{% endif %}">
                <a class="nav-link" href="{{ measurer_update }}">Actualizar medidor<i class="fas fa-tachometer-alt"></i></a>
            </li>
            <li class="nav-item {% if request.path == invoice_pay or request.path == invoice_list %}active{% endif %}">
                <div class="dropdown">
                    <div class="nav-link" data-toggle="dropdown">Facturas<i class="fas fa-clipboard-list"></i></div>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ invoice_pay }}">Pagar</a>
                        <a class="dropdown-item" href="{{ invoice_list }}">Listar </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <ul class="nav navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li class="navbar-item">
                <a href="{% url 'logout' %}" class="nav-link">
                    <i class="fas fa-sign-in-alt"></i>
                    Logout
                </a>
            </li>
        {% else %}
            <li class="navbar-item">
                <a href="{% url 'login' %}" class="nav-link {% if request.path == login %}active{% endif %}">
                    <i class="fas fa-user"></i>
                    Login
                </a>
            </li>
        {% endif %}
    </ul>
</nav>