houses/urls.py
from django.urls import path

from . import views

app_name = 'houses_visual'

urlpatterns = [
    path('crear/', views.visual_create, name='create')
]

water_control/urls.py
from django.contrib import admin
from django.urls import include, path


from django.conf import settings
from django.conf.urls.static import static
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('water_control.routes')),
    path('jefes-de-familia/', include('family_bosses.urls')),
    path('casas/', include('houses.urls')),
    path('medidores/', include('measurers.urls')),
    path('recibos/', include('invoices.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

houses/models.py
from django.db import models

from measurers.models import Measurer

from django.db.models.signals import pre_save

class House(models.Model):
    line1 = models.CharField(max_length=200, null=False, blank=False)
    line2 = models.CharField(max_length=200, null=True, blank=True)
    zip_code = models.CharField(max_length=20)
    house_id = models.CharField(max_length=20, unique=True)
    measurer = models.OneToOneField(Measurer, on_delete=models.CASCADE)

    def __str__(self):
        return self.house_id
    

def set_measurer(sender, instance, *args, **kwargs):
    if not instance.measurer:
        instance.measurer = Measurer.objects.create()

def upper_house_id(sender, instance, *args, **kwargs):
    if not instance.house_id:
        instance.house_id = instance.house_id.upper()

pre_save.connect(upper_house_id, sender=House)
pre_save.connect(set_measurer, sender=House)

houses/routes.py
from django.urls import path
from . import views

app_name = 'houses'

urlpatterns = [
    path('', views.HouseViewListCreate.as_view(), name='list'),
    path('<int:pk>/', views.HouseDetailView.as_view(), name='detail'),
]

houses/views.py
from django.shortcuts import render

from rest_framework import mixins
from rest_framework import generics

from .serializers import HouseSerializer

from .models import House
from measurers.models import Measurer

from django.contrib.auth.decorators import login_required
from rest_framework import permissions

class HouseViewListCreate(generics.ListCreateAPIView):
    permission_classes = [permissions.IsAuthenticated]
    queryset = House.objects.all()
    serializer_class = HouseSerializer

    def perform_create(self, serializer):
        serializer.save(measurer=Measurer.objects.create())

class HouseDetailView(mixins.ListModelMixin,
                  generics.GenericAPIView):
    permission_classes = [permissions.IsAuthenticated]
    queryset = House.objects.all()
    serializer_class = HouseSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

@login_required()
def visual_create(request):
    return render(request, 'houses/create.html')

houses/templates/houses/snippets/form.html
<form id="form_house" action="{% url 'houses:list' %}">
    <div class="form-group">
      <label for="">Calle 1:</label>
      <input required type="text" api="water_control" class="form-control" name="line1" id="line1" placeholder="Calle San Patricio">
    </div>

    <div class="form-group">
        <label for="">Calle 2:</label>
        <input type="text" api="water_control" class="form-control" name="line2" id="line2"placeholder="Calle Nueva Granada">
    </div>

    <div class="form-group">
        <label for="">Codigo Postal:</label>
        <input required type="text" api="water_control" class="form-control" name="zip_code" id="zipcode" placeholder="DXW-3301">
    </div>

    <div class="form-group">
        <label for="house">Identificación:</label>
        <input required type="text" api="water_control" class="form-control" name="house_id" id="house" aria-describedby="helpHouse" placeholder="ABC-123">
        <small id="helpHouse" class="form-text text-muted">El numero o alfanumerico de identificacion de la casa o establacimiento</small>
    </div>
  
    <button type="submit" class="btn btn-primary">Crear</button>

</form>